<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Aleo</string>
    <key>scopeName</key>
    <string>source.aleo</string>
    <key>scope</key>
    <string>source.aleo</string>
    <key>fileTypes</key>
    <array>
      <string>aleo</string>
    </array>
    <key>extension</key>
    <array>
      <string>aleo</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#block_comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#line_comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#finalize</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#qualifiers</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#visibility</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#instructions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#numbers</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>keywords</key>
      <dict>
        <key>name</key>
        <string>keyword.control.aleo</string>
        <key>match</key>
        <string>\b(function|program|as|by|interface|closure|into|import)\b</string>
      </dict>
      <key>finalize</key>
      <dict>
        <key>name</key>
        <string>finalize.aleo</string>
        <key>match</key>
        <string>\b(finalize|mapping|increment|decrement)\b</string>
      </dict>
      <key>qualifiers</key>
      <dict>
        <key>name</key>
        <string>qualifiers.aleo</string>
        <key>match</key>
        <string>\(|\)</string>
      </dict>
      <key>visibility</key>
      <dict>
        <key>name</key>
        <string>visibility.aleo</string>
        <key>match</key>
        <string>\b(constant|public|private|record|aleo)\b</string>
      </dict>
      <key>instructions</key>
      <dict>
        <key>name</key>
        <string>instruction.aleo</string>
        <key>match</key>
        <string>\b(abs\.w|abs|add\.w|add|and|assert\.eq|assert\.neq|call|cast|commit\.bhp256|commit\.bhp512|commit\.bhp768|commit\.bhp1024|commit\.ped64|commit\.ped128|div\.w|div|double|gt|gte|hash\.bhp256|hash\.bhp512|hash\.bhp768|hash\.bhp1024|hash\.ped64|hash\.ped128|hash\.psd2|hash\.psd4|hash\.psd8|inv|input|is\.eq|is\.neq|lt|lte|key|mod|mul\.w|mul|nand|neg|nor|not|or|output|pow\.w|pow|rem\.w|rem|shl\.w|shl|shr\.w|srh|sqrt|sub\.w|sub|square|ternary|value|xor)\b</string>
      </dict>
      <key>numbers</key>
      <dict>
        <key>name</key>
        <string>constant.numeric.aleo</string>
        <key>match</key>
        <string>-?[0-9.]+</string>
      </dict>
      <key>strings</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.aleo</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.aleo</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <key>block_comment</key>
      <dict>
        <key>comment</key>
        <string>Block comment</string>
        <key>name</key>
        <string>punctuation.definition.block.comment.aleo</string>
        <key>begin</key>
        <string>/\*</string>
        <key>end</key>
        <string>\*/</string>
      </dict>
      <key>line_comment</key>
      <dict>
        <key>comment</key>
        <string>Single-line comment</string>
        <key>name</key>
        <string>punctuation.definition.inline.comment.aleo</string>
        <key>begin</key>
        <string>//</string>
        <key>end</key>
        <string>$</string>
      </dict>
    </dict>
  </dict>
</plist>